version: '3.7'

services:
  postgres:
    image: postgres:11-alpine
    container_name: image2list-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    restart: always
    user: root

  pgadmin:
    image: dpage/pgadmin4:4
    container_name: image2list-pgadmin
    ports:
      - 80:80
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: root
    hostname: pgadmin
    restart: always
